### PR TITLE
Sensor choice with cmake and new wrapper for SoftKinetic

### PR DESCRIPTION
**Pull request by ph4m**
Hi Andrea, we've met at CVPR :)

I gave your tracker a try and noticed that the DepthSense camera didn't work quite as well as the PrimeSense/Xtion for your application. As I noticed your SoftKin class used some of the code I did for https://github.com/ph4m/DepthSenseGrabber, I extended it by creating a new sensor class named SensorDepthSenseGrabber which basically adds some filtering to the depth and color measurements to drastically improve the point cloud for tracking.

On the following pictures (SoftKin, then DepthSenseGrabber), notice the "doubled" little finger and arm on the initial color map, which I fixed using the confidence map from the SoftKinetic API. The density of the point cloud was also improved with a Butterworth low-pass temporal filter and a Gaussian spacial blur.

softkin
depthsensegrabber

I also added a new cmake script (ConfigureSensor.cmake) which lets you define which sensor you intend to use when generating your build environment, rather than having to manually modify the code and commenting/uncommenting #define REALSENSE before #if defined(REALSENSE) as it's done right at the moment.
Now, all you have to do is adding a cmake cache entry corresponding to your sensor, by doing for instance cmake -D SENSOR_REALSENSE=1 path_to_source, or ticking the checkbox corresponding to your sensor in cmake-gui.
You just need to do it once, and if later on you decide to use another sensor, the script will reset the corresponding cached variables so you just need to run it again with your new choice of sensor.

Let me know if you have any questions.

Cheers,

### CODE REVIEW

**Comment by taiya** [comment]
Awesome, indeed I didn't spend much time on the SoftKinetic (we only discovered we could work on it 2.5 weeks before the deadline). I think there is something broken in the published code though.. I've noticed it in the 2-hands interaction (something not working quite right with re-weighting).

I'll take a look at your merge request and bring it forth (i'll also acknowledge you on the main README.md clearly). The licence will be LGPL, haven't really bothered putting one in yet :)

**Comment by taiya** [comment]
I checked, and the reason was that the detection didn't work very well on the old creative camera. 
In the htrack_atb (there is 2 executables generated) if you disable the re-initialization (Detection ON?), then the tracking starts working quite well again.

But your fix definitely improves the performance of the detector :) (just tried it out)

**Comment by taiya** [comment]
Awesome. Just one thing... Do you think I should just remove the older SoftKinetic stuff? (or perhaps just rename the grabber you created into softkinetic...). I've noticed the failure detection metric are wrong for the **Senz3D**...

**Comment by ph4m** [comment]
I think you can safely remove the original SoftKin class, yes, as the additional functionalities offered by DepthSenseGrabber can be easily removed by commenting out the #define DEPTHSENSEGRABBER_SPECIAL_FEATURE lines so the compiler ignores them, if for some reason you wanted to fall back on the raw measurements.

**Comment by taiya** [comment]
Do you mind if I just rename it to SoftKinetic? (I'll put in a note about
the fact that it's your stuff)

**Comment by ph4m** [comment]
I'm fine with it, please do :)

**Pull request merged**
